spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    metadata-map.zone: ${ZONE_NAME}