spring:
  application:
    name: zone-info
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      preferSameZoneEureka: true
  instance:
    preferIpAddress: true
    metadata-map.zone: ${ZONE_NAME}